-- phpMyAdmin SQL Dump
-- version 5.0.2
-- https://www.phpmyadmin.net/
--
-- Hôte : 127.0.0.1:3306
-- Généré le : lun. 14 juin 2021 à 10:07
-- Version du serveur :  5.7.31
-- Version de PHP : 7.3.21

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données : `vietvodao`
--

-- --------------------------------------------------------

--
-- Structure de la table `specialist`
--

DROP TABLE IF EXISTS `specialist`;
CREATE TABLE IF NOT EXISTS `specialist` (
  `id` int(10) NOT NULL AUTO_INCREMENT,
  `name` text COLLATE utf8_unicode_ci NOT NULL,
  `pictureProfile` text COLLATE utf8_unicode_ci NOT NULL,
  `biographyShort` text COLLATE utf8_unicode_ci NOT NULL,
  `birthday` varchar(15) COLLATE utf8_unicode_ci NOT NULL,
  `deathDate` varchar(15) COLLATE utf8_unicode_ci DEFAULT NULL,
  `function` text COLLATE utf8_unicode_ci,
  `hierarchy` text COLLATE utf8_unicode_ci,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=20 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Déchargement des données de la table `specialist`
--

INSERT INTO `specialist` (`id`, `name`, `pictureProfile`, `biographyShort`, `birthday`, `deathDate`, `function`, `hierarchy`) VALUES
(2, 'Mạnh Hoàng', 'assets/img/maitres/manh_hoang.jpg', 'En 1960, Maître Mạnh Hoàng commençait à pratiquer le Vovinam Viet Vo Dao sur les conseils de son meilleur ami, Maître Trần Huy Phong. Grâce à ses bases très solides dans le judo et aux enseignements directs et spéciaux de Maître Trần Huy Phong, Maître Mạnh Hoàng avait franchi rapidement le niveau moyen dans le Vovinam Viet Vo Dao. En dehors de ses activités dans les arts martiaux, il enseignait les mathématiques et la physique-chimie dans les lycées de Saigon. De ce fait, avec un nombre de ses collègues enseignants comme les professeurs : Trần Huy Phong, Hoàng Quân, Đinh Đức Mậu, Nguyễn Văn Cường, Phan Quỳnh, Nguyễn Xuân Thiều, Mai Trung Hoa... ils créaient le Centre pédagogique pour le Grand Public en 1961.', '1938', '1967', 'Ceinture blanche suprême (1996), Ceinture rouge 1er degré (1964), Président de la Commission des relations extérieures, membre fondateur du premier Conseil des maitres du Vovinam VVD en 1964', 'great-master'),
(6, 'Trần Huy Quyền', 'assets/img/maitres/no-picture.png', 'Maître Trần Huy Quyền avait débuté dans le Vovinam Việt Võ Đạo en 1960, dans le Centre principal du Vovinam – le centre situé sur la rue Trần Hưng Đạo, SaiGòn – dont l’enseignement était dispensé par les maîtres Lê Sáng et Trần Huy Phong. Très talentueux pour les arts martiaux, un an après (décembre 1961) il était sélectionné pour faire partie de l’équipe de démonstration à la salle Olimpic (le premier song luyện avec son condisciple Thái đen) à l’occasion d’une œuvre caritative pour recueillir des fonds au secours des victimes de l’inondation au sud est du Vietnam.', '1945', '2001', 'Ceinture blanche suprême (2008), Ceinture rouge 1er degré (1989), Fondateur du Vovinam-Việt Võ Đạo en Australie, Vice-Président de la Fédération mondiale de Vovinam-VVĐ', 'great-master'),
(4, 'Trịnh Ngọc Minh', 'assets/img/maitres/no-picture.png', 'Maître Trịnh Ngọc Minh, de son vrai nom Trịnh Văn Mão, était décédé le 30 décembre 1998 (le 12 octobre de l’année du Tigre Mậu Dần) à Sài Gòn. Maître Trịnh Ngọc Minh était le fondateur du Vovinam-Việt Võ Đạo dans la région du Centre du Việt Nam. C’était un homme joyeuse, ouverte et vivante. Depuis son jeune âge, il vivait de manière autonome, travaillait pour suvenir les besoins de sa famille. Cette expérience de vie lui forgeait les vertus suivantes : la confiance, la perséverance et l’amour du travail.', '1939', '1998', 'Ceinture blanche suprême (2008), Ceinture rouge 2ème degré (1973), Directeur Technique de la région du centre du Vietnam (1967-1975)', 'great-master'),
(7, 'Lê Sang', 'assets/img/maitres/no-picture.png', 'Maître Patriarche Lê Sáng, né en 1920, a débuté dans le Vovinam VVD en 1940 à Hanoi Vietnam. Il est décédé le 27/09/2010 au Vietnam, à 90 ans. ', '1920', '27/09/2010', 'Patriarche (1964 -1986), Patriarche (1990 - 2010)', 'great-master'),
(5, 'Trần Đức Hợp', 'assets/img/maitres/no-picture.png', 'Le grand Maître Trần Đức Hợp est né le 3 septembre 1931 à Phuc Yen, au Nord du Vietnam. C’est l\'un des meilleurs disciples du maître Nguyễn Lộc. Il a débuté le Vovinam-Viet Vo Dao en 1948 au club de la rue Hang Than à Hanoi, en même temps que le grand maître Phan Dương Bình.', '1931', '2000', 'Ceinture Blanche Suprême (1996),Ceinture rouge 2ème degré (1967),Enseignant des Mousquetaires de l’ancien empereur Bảo Đại (1953),Disciple direct du maître fondateur Nguyễn Lộc (1948),Membre du Conseil Suprême des Maîtres', 'great-master'),
(8, 'Nguyễn Dần', 'assets/img/maitres/no-picture.png', 'Grand Maître Nguyễn Dần est né en 1928 au Nord du Vietnam. Il est le jeune frère et disciple du maître Nguyễn Lộc. Il a débuté le Vovinam à l’âge de 8 ans (1936), pendant la période de recherche et de structuration du Vovinam par maître Nguyễn Lộc.', '1928', '2016', 'Ceinture Blanche du Président du Conseil Mondial des Maîtres,Disciple direct du maître fondateur Nguyễn Lộc,Président de la Fédération Internationale de Vovinam-Viet Vo Dao (1990-1991),Président du Conseil Mondial des Maîtres (3 mandats 2004-2016)', 'great-master'),
(9, 'Ngô Kim Tuyền', 'assets/img/maitres/no-picture.png', 'Grand maître Ngô Kim Tuyền est né le 1er février 1947 à Quy Hau, district Kim Son, dans la province Ninh Binh au Vietnam. Il a débuté le Vovinam-Viet Vo Dao le 15 juillet 1965 au centre de Vinh Vien. Il est formé par maître Trần Huy Phong, Nguyễn Văn Thư et Lê Sáng.', '1947', '2019', 'Ceinture Blanche Suprême (2008),Ceinture rouge 2ème degré (1993),Directeur technique du Vovinam-Viet Vo Dao de la région Nord-Ouest du Vietnam (1970-1975)', 'great-master'),
(10, 'Nguyễn Văn Thông', 'assets/img/maitres/no-picture.png', 'Grand maître Nguyễn Văn Thông est né le 28 octobre 1925 à Hanoï, au Nord Vietnam, décédé le 7 septembre 2019 à Saigon. Disciple direct du maître fondateur Nguyễn Lộc, il a débuté le Vovinam en 1953 à rue Hang Bong, à Hanoï.', '1925', '2019', 'Ceinture Blanche Suprême (1996),Disciple direct du maître fondateur Nguyễn Lộc,Président de l\'association générale de Viet Vo Dao (1967-1975),Président de la Fédération de la Jeunesse Viet Vo Dao (1973-1975),Membre du Conseil Suprême des Maîtres', 'great-master'),
(11, 'Phan Dương Bình', 'assets/img/maitres/no-picture.png', 'Le grand maître Phan Dương Bình est né le 10 octobre 1929 à Hanoï, Vietnam. Il est l\'un des disciples hautement qualifiés du maître fondateur Nguyễn Lộc. Il a débuté en 1948, à l\'âge de 19 ans, en même temps que le grand maître Trần Đức Hợp (1931-2000), au club de la rue Hang Than, à Hanoï.', '1929', '2020', 'Ceinture Blanche Suprême (1996),Disciple direct du maître fondateur Nguyễn Lộc,Membre fondateur du Conseil Mondial des Maîtres et de la Fédération Mondiale de Vovinam-Viet Vo Dao, Paris -1996,Vice-président du Conseil Suprême des Maîtres (mandats 2008-2012 et 2012-2016),Reconnaissance au titre de Grand Maître International (10ème Dang) par l\'État Vietnamien à travers le Comité Olympique vietnamien et la Fédération Mondiale de Vocotruyen en 2015', 'great-master'),
(12, 'Lê Văn Phúc', 'assets/img/maitres/no-picture.png', 'Maître Lê Văn Phúc est non seulement un grand maître du Vovinam-Viet Vo Dao, mais aussi un poète, un écrivain, un journaliste pour de nombreux journaux et radios dans des pays comme États-Unis, Canada, Australie et Grande Bretagne (station de radio BBC).', '1934', '2020', 'Ceinture Blanche Suprême (1996),Disciple direct du maître fondateur Nguyễn Lộc,Membre dirigeant du Conseil Mondial des Maîtres (mandats 1996-2000 et 2000-2004),Membre du Conseil Suprême des Maîtres', 'great-master'),
(1, 'Trần Huy Phong', 'assets/img/maitres/no-picture.png', 'Maître Trần Huy Phong est né le 28 décembre 1938 dans la ville de Quan Phuong Trung, district Hai Hau, province Nam Dinh, au Nord Vietnam. De son vrai nom Trần Trọng Bách, modifié plus tard en Trần Quốc Huy, il est le quatrième d’une famille de sept enfants.', '1938', '1997', 'Patriarche du Vovinam-Viet Vo Dao (1986-1990),Ceinture rouge 5ème degré (9ème Dang international - 1973),Ceinture Blanche Suprême (10ème Dang international - 1990)', 'great-master'),
(3, 'Trần Nguyên Đạo', 'assets/img/maitres/Grand-Maitre TRAN Nguyen Dao.png', 'Maître Trần Nguyên Đạo a débuté le Vovinam-Viet Vo Dao en 1964 à Ban Me Thuot, Vietnam, sous l\'enseignement de son grand frère, maître Trần Huy Quyền (1945-2001). Issu d\'une famille très attachée aux arts martiaux par une très longue tradition familiale remontant au XIIe siècle, maître Dao est le benjamin de six frères qui ont tous atteint un haut niveau dans le Vovinam-Viet Vo Dao. ', '---', '---', '1985- 2000 : président du Conseil des Maîtres de France,1990-1992 : président du Conseil des Maîtres d’Europe,2000-2004 : président de la Fédération Mondiale de Vovinam-Viet Vo Dao,2004-2016 : secrétaire général du Conseil Mondial des Maîtres de Vovinam-Viet Vo Dao (3 mandats successifs),Depuis 2004 : président de la Commission Technique Internationale,Depuis 2015 : président du Conseil Consultatif de la Fédération Mondiale Vocotruyen (WFVV)', 'great-master'),
(13, 'Ha Kim Khanh', 'assets/img/maitres/Maitre HA Kim Khanh.png', 'Maître Ha Kim Khanh est né le 11 décembre 1952 à Saigon, capitale du Sud-Vietnam. Il est l’aîné d’une famille de 5 enfants (2 garçons et 3 filles) originaire du delta du Mékong, Sud-Vietnam.\r\nSon jeune frère, Maître Ha Kim Chung, pratique également le Vovinam Viet Vo Dao et enseigne à Limoges - France - avec le grade de Ceinture rouge 2ème degré (6ème Dang) et la fonction d’expert international chargé du développement au Maroc.\r\n\r\nMaître Khanh s’est initié à l’art martial à la fin des années 1960 avec son oncle qui pratique le style Binh Dinh (art martial vietnamien traditionnel du centre du Vietnam) et ses cousins qui pratiquent le Karaté. \r\n', '11/12/1952', '---', 'Président fondateur de plusieurs associations et clubs dans le Limousin (1972-1985),\r\nMembre fondateur de l’école Viet Vo Dao Nghia Long (1973),\r\nMembre fondateur de la Fédération Française de Viet Vo Dao (1973),\r\nEnseignant dans plusieurs clubs en Limousin - Poitou - Charentes (1973-1985),\r\nMembre de l’Equipe Mobile Européenne de Viet Vo Dao (1974-1980),\r\nResponsable des Examens du Comité Atlantique (1978-1985),\r\nDirecteur technique du Comité du Limousin (1980-1985),\r\nMembre fondateur de la Fédération Vovinam France (1985),\r\nPrésident du Conseil des Maîtres d’Europe (1992-1994),\r\nSecrétaire Général de la Fédération Mondiale (2000-2008),\r\nPrésident du Conseil des Maîtres de France (2010-2016),\r\nTrésorier de la Fédération Mondiale (2012-2016),\r\nSecrétaire Général du Conseil Mondial des Maîtres (depuis juillet 2016),', 'master'),
(14, 'Amar Guerrib', 'assets/img/maitres/Maitre GUERRIB Amar.png', 'Maître Guerrib Amar est né le 06 février 1969 à Longjumeau - France. Il est le cinquième d’une famille de 7 enfants (4 garçons et 3 filles) ses parents originaire d’Algérie ont quitté ce pays au cours des années 1965-1970 pour venir s’installer en France.\r\n\r\nC’est en 1984 à l’âge de 14 ans, que Maître Amar débute les arts martiaux vietnamien au sein de la Fédération Française de Viet Vo Dao dans un club de la région parisienne dont l’enseignement était dispensé par maître Petersen Phi-long (Léon), pilier au début des années 1970 du développement des arts martiaux vietnamiens et notamment du Vovinam-Việt Võ Đạo en France. \r\n', '06/02/1969', '---', 'Ceinture rouge 2ème degré (ceinture noire 6ème Dang),\r\nResponsable Technique National depuis 2014,\r\nResponsable technique de la région Île-de-France (2005-2014),\r\nResponsable technique de la région Basse-Normandie (1995-2001),\r\nVice-président de la Fédération Vovinam-VVD France (mandats 2012/2014 et 2008/2012),\r\nMembre titulaire du Conseil National des Maîtres de Vovinam-VVD,\r\nMembre du Conseil Mondial des Maîtres de Vovinam-VVD,\r\n', 'master'),
(15, 'Gilles Le Chevallier', 'assets/img/maitres/Maitre LECHEVALLIER Gilles.png', '', '--/--/1956', '---', 'Président du Comité Ile de France VVN VVD,\r\nPrésident du club de Maisse,\r\nEnseignant principal du club de Maisse 91720,\r\nPrésident de la ligue Régional Ile de France des Arts Martiaux Traditionnels Vietnamiens,', 'master'),
(16, 'Angela Nagot', 'assets/img/maitres/Maitre NAGOT Angela.png', 'Maitre NAGOT Angela a effectué toute sa pratique sous l’enseignement de MAITRE TRAN Nguyen Dao\r\n', '--/--/----', '---', 'Fondateur du Club AVVVD Paris 12ème - Présidente et Enseignante,\r\nCo membre Fondateur de la Fédération Vovinam France – Trésorière,\r\nCo membre Fondateur du Comité Ile de France - Trésorière,\r\nCo fondatrice et Enseignante du Club UMS Pontault Combault section Viet Vo Dao – Trésorière,\r\nOrganisation des évènements afférents à l’expansion de notre Art Martial et participation,', 'master'),
(17, 'Serge Crozon-Cazin', 'assets/img/maitres/Maitre CROZON-CAZIN Serge.png', 'J’ai débuté la pratique du Vovinam Viet vo dao en septembre 1984, avec les professeurs phi long et\r\nFélicita PETERSEN, puis avec Me Tran Nguyen Dao après l’obtention de ma ceinture noire en 1989. Un\r\npremier voyage au Viêtnam en 1993 à renforcé mon attachement à la discipline et le désir d’aller\r\nencore plus loin dans ma pratique du Vovinam Viet vo dao. Aujourd’hui, j’exerce un métier que je dois\r\nprofondément à ma pratique de cet arts martial.', '18/11/1969', '---', 'Président de l’AECAM VVD LONGJUMEAU,\r\nResponsable technique de la région Iles de France,\r\nResponsable technique national en charge des compétitions de combats adultes (FAMTV),\r\nExpert international chargé du développement au Sénégal,\r\nMembre du conseil Mondial des Maitres,\r\nMembre du conseil National des Maitres,', 'master'),
(18, 'Bruno De Brou', 'assets/img/maitres/Maitre DEBROU Bruno.png', '', '--/--/1970', '---', 'Président et Enseignant au club de CAEN, Normandie,\r\nMembre de la Fédération Vovinam France depuis 2003,', 'master'),
(19, 'Nguyen Thé Truong', 'assets/img/maitres/Grand-Maitre NGUYEN Thé Truong.png', 'Maître Nguyen The Truong (Thierry) a débuté à l’âge de sept ans dans la boxe libre auprès de son père et de son grand frère.\r\nEn 1965, il commence le Taekwondo avec Maître Nguyen Binh, puis Maître Dang Huy Duc à Saigon, Vietnam.\r\nArrivé en France en 1974 pour suivre des études supérieures, Maître Nguyen The Truong a profité de l’occasion pour développer les arts martiaux vietnamiens. Il a souhaité montrer qu’à travers sa pratique et ses connaissances sur les aspects techniques, philosophiques des arts martiaux vietnamiens, un autre visage de son pays.', '---', '---', 'Fondateur du Vovinam Viet Vo Dao Rhône Alpes Bourgogne en 1975,\r\nMembre du Conseil national des Maîtres,\r\nPrésident de la fédération Vovinam Viet Vo Dao France (1985 – 1992),\r\nPrésident de la fédération européenne de Vovinam Viet Vo Dao (1992- 1996),\r\nMembres du Conseil mondial des Maîtres,\r\nPrésident de la fédération mondiale de Vovinam Viet Vo Dao (depuis 2004),', 'great-master');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
